### ISSUE TITLE
Latest code is not published to hex

### ISSUE THREAD

**Issue by domnantas** [Matt-Hornsby/aprs_parse#1]
Hi! I'm using this package 0.1.0 version from hex and I'm getting the debug message spam. It seems the issue has been fixed in this commit: https://github.com/Matt-Hornsby/aprs_parse/commit/39e9d7353c73b85a16d6b98e8ac7e779665c8b55
However, it seems the code is yet to be published

**Comment by Matt-Hornsby** [comment]
Thanks @domnantas - I’ll take a pass at this and see if there’s anything else to clean up as well, and get a new version published

**Comment by Matt-Hornsby** [comment]
@domnantas published v0.1.1 - please take a look and let me know if this helps.

**Comment by domnantas** [comment]
Yep, looks good now, thanks!

I'm new to Elixir, and so far it's been a great learning experience. I'm building [OGN](http://wiki.glidernet.org/) viewer. Its packets include some additional data compared to regular APRS. Your project gives me a good foundation to build on top of, thanks!
